// In-memory mock database. Resets when the dev server restarts.
// TODO: delete this file when the real Supabase backend lands.

const store =
  globalThis.__mockDb ??
  (globalThis.__mockDb = { headlines: [], swipes: [], users: [], nextId: 1 });

// --- users & tiers -------------------------------------------------------
// First N signups are free forever; later users need a $14/mo subscription.
export const FREE_FOREVER_SEATS = 5;
export const FREE_HEADLINES_PER_MONTH = 10;

// Registers the user on first sight, preserving signup order.
export function ensureUser(userId, email) {
  store.users ??= [];
  let u = store.users.find((u) => u.id === userId);
  if (!u) {
    u = {
      id: userId,
      email,
      signup_index: store.users.length, // 0-based signup order
      subscribed: false,
      brand_voice: "",
      created_at: new Date().toISOString(),
    };
    store.users.push(u);
  }
  return u;
}

export function getUserCount() {
  return (store.users ?? []).length;
}

// Tier: 'free_forever' (first seats) | 'pro' (subscribed) | 'free'
export function getTier(userId) {
  const u = (store.users ?? []).find((u) => u.id === userId);
  if (!u) return "free";
  if (u.signup_index < FREE_FOREVER_SEATS) return "free_forever";
  return u.subscribed ? "pro" : "free";
}

export function isUnlimited(userId) {
  return getTier(userId) !== "free";
}

export function setSubscribed(userId, subscribed) {
  const u = (store.users ?? []).find((u) => u.id === userId);
  if (u) u.subscribed = subscribed;
  return u;
}

export function setBrandVoice(userId, text) {
  const u = (store.users ?? []).find((u) => u.id === userId);
  if (u) u.brand_voice = text;
  return u;
}

export function getBrandVoice(userId) {
  return (store.users ?? []).find((u) => u.id === userId)?.brand_voice ?? "";
}

// Headlines generated by this user in the current calendar month.
export function headlinesThisMonth(userId) {
  const now = new Date();
  return store.headlines.filter((h) => {
    if (h.user_id !== userId) return false;
    const d = new Date(h.created_at);
    return d.getFullYear() === now.getFullYear() && d.getMonth() === now.getMonth();
  }).length;
}

// --- headlines & swipes --------------------------------------------------

export function getHeadlines(userId) {
  return store.headlines.filter((h) => h.user_id === userId);
}

export function insertHeadlines(rows) {
  const now = new Date().toISOString();
  for (const row of rows) {
    store.headlines.push({ id: store.nextId++, created_at: now, ...row });
  }
}

export function getSwipes(userId) {
  return store.swipes.filter((s) => s.user_id === userId);
}

export function insertSwipe(row) {
  // store may predate the swipes array in a warm dev server
  store.swipes ??= [];
  const swipe = { id: store.nextId++, created_at: new Date().toISOString(), ...row };
  store.swipes.push(swipe);
  return swipe;
}
